### ISSUE TITLE
It "resets" all fields after building the plugin

### ISSUE THREAD

**Issue by ljfreelancer88** [Tmeister/wppb-generator#3]
BTW, thank you for this tool. My only concern is it resets all fields after building the plugin. Kindly, leave it as-is.

**Comment by junaidkbr** [comment]
@Tmeister Your opinion on this? If you approve, I can take over the issue.

**Comment by Tmeister** [comment]
Fixed on https://github.com/Tmeister/wppb-generator/commit/d5090994af43614fab0c7a2ac64739253fb7ad99
